USE QuanLySinhVien;
SELECT ADDRESS, COUNT(STUDENTID) AS so_luong_sinh_vien
FROM STUDENT
GROUP BY ADDRESS;
SELECT S.STUDENTID, S.STUDENTNAME, AVG(MARK)
FROM STUDENT S JOIN MARK M ON S.STUDENTID = M.STUDENTID
GROUP BY S.STUDENTID, S.STUDENTNAME;
SELECT S.STUDENTID, S.STUDENTNAME, AVG(MARK)
FROM STUDENT S JOIN MARK M ON S.STUDENTID = M.STUDENTID
GROUP BY S.STUDENTID, S.STUDENTNAME
HAVING AVG(MARK) > 15;
SELECT S.STUDENTID, S.STUDENTNAME, AVG(MARK)
FROM STUDENT S JOIN MARK M ON S.STUDENTID = M.STUDENTID
GROUP BY S.STUDENTID, S.STUDENTNAME
HAVING AVG(MARK) >= ALL (SELECT AVG(MARK) FROM MARK GROUP BY MARK.STUDENTID);