USE QUANLYSINHVIEN;
SELECT *,MAX(CREDIT) AS LARGESTCREDIT 
FROM SUBJECT
GROUP BY SUBID,SUBNAME
HAVING MAX(CREDIT) >= ALL (
	SELECT MAX(CREDIT) 
    FROM SUBJECT 
    GROUP BY SUBID,SUBNAME
);
SELECT S.SUBID,S.SUBNAME, S.CREDIT, S.STATUS, MAX(MARK) AS HIGHEST_MARK
FROM SUBJECT S JOIN MARK M ON S.SUBID = M.SUBID
GROUP BY SUBID
HAVING MAX(MARK) >= ALL (
SELECT MAX(MARK)
FROM MARK
GROUP BY SUBID
);
SELECT S.STUDENTID, S.STUDENTNAME, S.ADDRESS, S.PHONE, S.STATUS, S.CLASSID, AVG(MARK) AS AVERAGE_MARK
FROM STUDENT S JOIN MARK M ON S.STUDENTID = M.STUDENTID
GROUP BY STUDENTID
HAVING AVG(MARK) >= ALL (
SELECT AVG(MARK)
FROM MARK
GROUP BY STUDENTID
)
ORDER BY AVG(MARK) DESC;