use quanlydiemthi;
CREATE TABLE Hocsinh(
MaHS VARCHAR(20) PRIMARY KEY,
TenHS VARCHAR(50),
NgaySinh DATETIME,
Lop VARCHAR(20),
GT VARCHAR(20)
);
CREATE TABLE MonHoc(
MaMH VARCHAR(20) PRIMARY KEY,
TenMH VARCHAR(50)
);
CREATE TABLE BangDiem(
MaHS VARCHAR(20),
MaMH VARCHAR(20),
DiemThi INT,
NgayKT DATETIME,
PRIMARY KEY (MaHS,MaMH),
FOREIGN KEY (MaHS) REFERENCES hocsinh(MaHS),
FOREIGN KEY (MaMH) REFERENCES MonHoc(MaMH)
);
CREATE TABLE giaovien(
MaGV VARCHAR(20) PRIMARY KEY,
TenGV VARCHAR(20),
SDT VARCHAR(10)
);
ALTER TABLE monhoc ADD MaGV VARCHAR(20);
ALTER TABLE monhoc ADD constraint FK_MaGV FOREIGN KEY (MaGV) references giaovien(MaGV);
