create database quanlysinhvien;
use quanlysinhvien;
create table class (
CLASSID INT NOT NULL auto_increment primary key,
CLASSNAME VARCHAR(60) NOT NULL,
STARTDATE DATETIME NOT NULL,
STATUS BIT
);
CREATE TABLE STUDENT(
STUDENTID INT NOT NULL auto_increment primary KEY,
STUDENTNAME VARCHAR(30) NOT NULL,
ADDRESS VARCHAR(50),
PHONE VARCHAR(20),
STATUS BIT,
CLASSID INT NOT NULL,
foreign key (CLASSID) references CLASS (CLASSID)
);
CREATE TABLE SUBJECT(
SUBID INT auto_increment NOT NULL primary key,
SUBNAME VARCHAR(30) NOT NULL,
CREDIT tinyint NOT NULL default 1 CHECK (CREDIT >= 1),
STATUS BIT DEFAULT 1
);
CREATE TABLE MARK(
MARKID INT NOT NULL auto_increment PRIMARY KEY,
SUBID INT NOT NULL,
STUDENTID INT NOT NULL,
MARK FLOAT DEFAULT 0 CHECK (MARK between 0 AND 100),
EXAMTIMES TINYINT default 1,
UNIQUE (SUBID, STUDENTID),
foreign key (SUBID) references SUBJECT (SUBID),
foreign key (STUDENTID) references STUDENT(STUDENTID)
);