CREATE DATABASE IF NOT EXISTS shopee;
USE shopee;
CREATE TABLE IF NOT EXISTS CATEGORY (
ID INT AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
PRIMARY KEY(ID)
);
CREATE TABLE IF NOT EXISTS PRODUCT (
ID INT AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
PRICE BIGINT DEFAULT 0 CHECK (PRICE >= 0),
CATEGORY_ID INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);
CREATE TABLE IF NOT EXISTS VARIANT (
ID INT AUTO_INCREMENT,
COLOR VARCHAR(20) NOT NULL,
SIZE VARCHAR(20) NOT NULL,
PRODUCT_ID INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);
CREATE TABLE IF NOT EXISTS CUSTOMER (
ID INT AUTO_INCREMENT,
USER_NAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
PHONE VARCHAR(11) ,
PRIMARY KEY(ID)
);
CREATE TABLE IF NOT EXISTS ADDRESS (
ID INT AUTO_INCREMENT,
NUMBER INT NOT NULL,
STREET VARCHAR (255) NOT NULL,
CUSTOMER_ID INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);
CREATE TABLE IF NOT EXISTS CART (
ID INT AUTO_INCREMENT,
TOTAL_PRICE INT NOT NULL,
CUSTOMER_ID INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);
CREATE TABLE IF NOT EXISTS CART_LINE_ITEM (
ID INT AUTO_INCREMENT,
CART_ID INT NOT NULL,
VARIANT_ID INT NOT NULL,
QUANTITY INT DEFAULT 1,
TOTAL_PRICE INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (CART_ID) REFERENCES CART(ID),
FOREIGN KEY (VARIANT_ID) REFERENCES VARIANT(ID)
);