DELIMITER $$

DROP PROCEDURE IF EXISTS `sinhvien`.`getTenSV` $$
CREATE PROCEDURE `sinhvien`.`getTenSV` 
   (IN MS_SINHVIEN INT, OUT TEN_SINHVIEN VARCHAR(255))
BEGIN
   SELECT ten INTO TEN_SINHVIEN
   FROM sinhvienk60
   WHERE MSSV = MS_SINHVIEN;
END $$

DELIMITER ;