USE QUANLYSINHVIEN;
SELECT * FROM STUDENT 
WHERE STUDENTNAME LIKE 'H%';
SELECT * FROM CLASS
WHERE STARTDATE LIKE '%12%';
SELECT * FROM SUBJECT
WHERE CREDIT > 2 AND CREDIT < 6;
UPDATE STUDENT 
SET CLASSID = 2
WHERE STUDENTID = 1;
SELECT S.STUDENTNAME, SUB.SUBNAME, M.MARK 
FROM STUDENT S JOIN MARK M ON S.STUDENTID = M.MARKID JOIN SUBJECT SUB ON M.SUBID = SUB.SUBID
ORDER BY MARK DESC, STUDENTNAME ASC;